version: '3.8'

services:
  web:
    build: .
    command: gunicorn myproject.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app/
    ports:
      - 8000:8000
    depends_on:
      - redis
    networks:
      - back-end

  redis:
    image: redis
    networks:
      - back-end

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./static:/static
    depends_on:
      - web
    networks:
      - front-end
      - back-end

networks:
  front-end:
  back-end:

